### ISSUE TITLE
samples inclusion in tarball

### ISSUE THREAD

**Issue by pgajdos** [dmedvinsky/mutt-ics#19]
Could you please consider to add samples/ in the tarball?

**Comment by dmedvinsky** [comment]
Which tarball are you talking about? The one published on PyPI? Why would you want the samples in there? They are there for development reasons. And the contributors are supposed to use the repo clone.

**Comment by pgajdos** [comment]
Yes, the one published on PyPI. I am thinking about implementing a smoke test in check phase of package build.

If you do not want to include it, feel free to close this ticket, I will do other way.

**Comment by dmedvinsky** [comment]
Well, seems like a legit use case. I don't think it is going to hurt, so I've included the samples in the new package.

**Comment by pgajdos** [comment]
Thanks!
