### ISSUE TITLE
Reply to calendar invitations

### ISSUE THREAD

**Issue by timhae** [dmedvinsky/mutt-ics#24]
Thanks for the script, it is really helpful. I was wondering, how can I reply 'accept' or 'decline' to outlook invitations, do you know how that works?

**Comment by tuxun** [comment]
I'm not sure but I think you have to replace your "PARTSTAT=NEEDS-ACTION" with "PARTSTAT=ACCEPTED" in the file, then send it back to the meeting creator/manager. 

[](https://www.ietf.org/rfc/rfc5545.txt)

**Comment by timhae** [comment]
thanks, will try that
