### ISSUE TITLE
Info to add alternative_order to muttrc

### ISSUE THREAD

**Issue by aleshorak** [dmedvinsky/mutt-ics#26]
According to https://github.com/asciipip/mutt-ical (and to my testing of mutt-ics), it is useful to add

```alternative_order text/calendar text/plain text/html```

to the `muttrc` config file, to prefer the `text/calendar` format view instead of its textual counterparts in `multipart/alternative` e-mails (which is what e.g. Outlook calendar generates). Otherwise, you have to navigate to the `text/calendar` attachment explicitly.

**Comment by dmedvinsky** [comment]
Any chance you care to make a pull request? 🙂

**Comment by aleshorak** [comment]
Well, this is just about adding 4 lines to the README.md:

  3. For `multipart/alternative` e-mails (which is what e.g. Outlook calendar generates), you 
      probably want to prefer the `text/calendar` format view instead of its textual counterparts. 
      For such settings add another line to the `.muttrc` config file:

          alternative_order text/calendar text/plain text/html
