### ISSUE TITLE
Any way to view both html and ics?

### ISSUE THREAD

**Issue by nealmcb** [dmedvinsky/mutt-ics#5]
This is very helpful - thanks!

I most commonly get emails with a multipart-alternative combination of html and plain and ics.  Now when I select the ics attachment, I see the calendar information, nicely formatted, which is very nice.

But by default, mutt only shows me the html content (via w3m), since I have this in my .muttrc:

```
alternative_order text/html text/enriched text/plain text
```

Is there any way to configure mutt so that I view _both_ the html content and the ics content, one before the other, by default?

**Comment by protist** [comment]
@nealmcb Did you ever find a way to do this? I can't find a way to display the email body and the ics both in-line. FWIW I prefer plain mail first myself, with the following in my `muttrc`
```
alternative_order text/plain text/enriched text/html
```
This will only display `text/plain`. However, even if I remove it, it only displays the ics, and no body.

Perhaps this is a problem in the sent mail… the ones I've received are sent as `multipart/alternative`, with subgroups of `text/plain`, `text/html`, and `text/calendar`. I guess mutt wants to display one of the "alternatives", but I wonder if there's a way to show more than one.
