### ISSUE TITLE
utf-8?

### ISSUE THREAD

**Issue by donnm** [dmedvinsky/mutt-ics#6]
I have a calendar entry with Norwegian characters in the DESCRIPTION part (ø,æ,å) and this causes the script to abort.

**Comment by donnm** [comment]
Fixed it, patch below. Not sure if it's the best way to do it but it works for me.

$ diff mutt-ics/src/main.py bin/mutt-ics/src/main.py
87c87,89
<             res.append(u'%s:%s%s' % (k.capitalize(), pad, str(v)))
---
>             #res.append(u'%s:%s%s' % (k.capitalize(), pad, str(v)))
>             print k.encode('utf-8'), pad, v.encode('utf-8')
>             res.append('%s:%s%s' % (k.encode('utf-8').capitalize(), pad, v.encode('utf-8')))
101c103
<             return 'Participants:\n%s' % "\n".join(people)
---
>             return 'Participants:\n%s' % "\n".join(people).encode('utf-8')
107c109
<         description = e['DESCRIPTION'].strip()
---
>         description = e['DESCRIPTION'].strip().encode('utf-8')

**Comment by lxsli** [comment]
The above patch didn't work for me. I played around with Python for a bit, but in the end the answer needs to go in the show_ics script:

    export PYTHONIOENCODING=utf-8

**Comment by donnm** [comment]
That doesn't work for me:

Traceback (most recent call last):
  File "/home/user/bin/mutt-ics/src/main.py", line 130, in <module>
    main(sys.argv)
  File "/home/user/bin/mutt-ics/src/main.py", line 126, in main
    output = get_interesting_stuff(cal)
  File "/home/user/bin/mutt-ics/src/main.py", line 49, in get_interesting_stuff
    c = get_component(component)
  File "/home/user/bin/mutt-ics/src/main.py", line 62, in get_component
    return get_event(component)
  File "/home/user/bin/mutt-ics/src/main.py", line 113, in get_event
    result = filter(bool, [get_header(e),
  File "/home/user/bin/mutt-ics/src/main.py", line 87, in get_header
    res.append(u'%s:%s%s' % (k.capitalize(), pad, str(v)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 4: ordinal not in range(128)

**Comment by dmedvinsky** [comment]
@donnm Can you post the faulty ics file somewhere (here or a gist maybe?). Of course you should strip any private info from it, so it just barely crashes the script.

**Comment by donnm** [comment]
Here you go:

BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VEVENT
DESCRIPTION;LANGUAGE=en-US:When: Tuesday\, February 17\, 2015 2:00 PM-3:00
 PM. (UTC+01:00) Amsterdam\, Berlin\, Bern\, Rome\, Stockholm\, Vienna\nWhe
 re: XXX\n\n*~*~*~*~*~*~*~*~*~*\n\n Norwegian characters æ ø å\n
SUMMARY;LANGUAGE=en-US:æ ø å
END:VEVENT
END:VCALENDAR

**Comment by dmedvinsky** [comment]
@donnm Hey, could you try it with the latest master? I just pushed a fix and it seems to work for me on both 2.7 and 3.4.

**Comment by donnm** [comment]
Yes, works now, thanks!

**Comment by dmedvinsky** [comment]
Great, thanks.

**Comment by dmedvinsky** [comment]
@lxsli Would be great if you tried it, too.

**Comment by lxsli** [comment]
Yep looks good to me.

On 16 February 2015 at 08:13, Dmitry Medvinsky <notifications@github.com>
wrote:

> @lxsli <https://github.com/lxsli> Would be great if you tried it, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmedvinsky/mutt-ics/issues/6#issuecomment-74472359>.
>



-- 
Alexis

**Comment by dmedvinsky** [comment]
Cool, thanks.
